name: SWAG (Secure Web Application Gateway)
website_url: https://github.com/linuxserver/docker-swag
description: Nginx webserver and reverse proxy with PHP support, built-in Certbot (Let's Encrypt) client and fail2ban integration.
licenses:
  - GPL-3.0
platforms:
  - Docker
tags:
  - Web Servers
source_code_url: https://github.com/linuxserver/docker-swag
stargazers_count: 3523
updated_at: '2025-12-13'
archived: false
current_release:
  tag: 5.2.2-ls425
  published_at: '2025-12-13'
commit_history:
  2025-01: 38
  2025-02: 11
  2025-03: 10
  2025-04: 9
  2025-05: 11
  2025-06: 11
  2025-07: 22
  2025-08: 8
  2025-09: 5
  2025-10: 6
  2025-11: 13
  2025-12: 4
