name: SWAG (Secure Web Application Gateway)
website_url: https://github.com/linuxserver/docker-swag
description: Nginx webserver and reverse proxy with PHP support, built-in Certbot (Let's Encrypt) client and fail2ban integration.
licenses:
  - GPL-3.0
platforms:
  - Docker
tags:
  - Web Servers
source_code_url: https://github.com/linuxserver/docker-swag
stargazers_count: 3193
updated_at: '2025-04-08'
archived: false
