name: SWAG (Secure Web Application Gateway)
website_url: https://github.com/linuxserver/docker-swag
description: Nginx webserver and reverse proxy with PHP support, built-in Certbot (Let's Encrypt) client and fail2ban integration.
licenses:
  - GPL-3.0
platforms:
  - Docker
tags:
  - Web Servers
source_code_url: https://github.com/linuxserver/docker-swag
stargazers_count: 3500
updated_at: '2025-11-22'
archived: false
current_release:
  tag: 5.1.0-ls420
  published_at: '2025-11-22'
commit_history:
  2025-08: 7
  2025-09: 5
  2025-10: 6
  2025-11: 12
