name: Traefik
website_url: https://traefik.io/
source_code_url: https://github.com/traefik/traefik
description: HTTP reverse proxy and load balancer that makes deploying microservices easy.
licenses:
  - MIT
platforms:
  - Go
  - Docker
tags:
  - Web Servers
stargazers_count: 57637
updated_at: '2025-10-28'
archived: false
current_release:
  tag: v3.6.0
  published_at: '2025-11-07'
commit_history:
  2025-08: 31
  2025-09: 34
  2025-10: 66
  2025-11: 0
