name: Traefik
website_url: https://traefik.io/
source_code_url: https://github.com/traefik/traefik
description: HTTP reverse proxy and load balancer that makes deploying microservices easy.
licenses:
  - MIT
platforms:
  - Go
  - Docker
tags:
  - Web Servers
stargazers_count: 58486
updated_at: '2025-11-07'
archived: false
current_release:
  tag: v3.6.1
  published_at: '2025-11-13'
commit_history:
  2025-08: 31
  2025-09: 34
  2025-10: 70
  2025-11: 11
