name: Traefik
website_url: https://traefik.io/
source_code_url: https://github.com/traefik/traefik
description: HTTP reverse proxy and load balancer that makes deploying microservices easy.
licenses:
  - MIT
platforms:
  - Go
  - Docker
tags:
  - Web Servers
stargazers_count: 61865
updated_at: '2026-02-20'
archived: false
current_release:
  tag: v3.6.8
  published_at: '2026-02-11'
commit_history:
  2025-03: 38
  2025-04: 34
  2025-05: 34
  2025-06: 36
  2025-07: 45
  2025-08: 31
  2025-09: 34
  2025-10: 70
  2025-11: 37
  2025-12: 60
  2026-01: 86
  2026-02: 28
